
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: boardgamer_dev

test:
  <<: *default
  database: boardgamer_test

# production:
  # <<: *default
  # database: db/production.sqlite3
